{
 "title": "[Itaú] - Twitter API Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests  per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_http_requests_total{proxy=\"api-server_fe\"}[20s])*60/10",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_response_time_average_seconds{proxy=\"api-server_be\"}",
     "legendFormat": "Average response time"
    },
    {
     "expr": "haproxy_backend_max_total_time_seconds{proxy=\"api-server_be\"}",
     "legendFormat": "Max response time"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_http_responses_total{code=\"5xx\",proxy=\"api-server_be\"}[5m])",
     "legendFormat": "5XX Errors"
    }
   ]
  }
 ]
}