global:
  scrape_interval: 10s
  scrape_timeout: 8s
  evaluation_interval: 15s

scrape_configs:
- job_name: api_server_health
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://api_server:8000/api/health
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
- job_name: api_server_endpoints
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://api_server:8000/api/v1/users
      - http://api_server:8000/api/v1/hour
      - http://api_server:8000/api/v1/tags
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
- job_name: haproxy
  metrics_path: /metrics
  static_configs:
    - targets:
      - haproxy:8404