# Generated by Django 3.0.8 on 2020-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=280)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('username', models.CharField(max_length=16)),
                ('language', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=128)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
    ]
