# Generated by Django 3.0.8 on 2020-07-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20200705_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='language',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
